apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy
  namespace: sujith
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: gar-connection
      containers:
      - name: c23
        image: us-central1-docker.pkg.dev/winter-monolith-477705-m8/resp/python22
        ports:
        - containerPort: 5000
